server:
  port: 9001
spring:
  application:
    name: user-auth
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mininote_oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: mininote
  clientSecret: mininote #密钥
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/mininote.jks  #证书位置
    secret: mininote  #密钥
    alias: mininote
    password: mininote

#开启容断器
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 熔断超时设置，默认为1秒
            timeoutInMilliseconds: 10000
          #  隔离模式使用信号量隔离SEMAPHORE 默认值是线程隔离THREAD
          strategy: SEMAPHORE
#logging:
#  level:
#    com:
#      mininote:
#        oauth:
#          dao: debug