server:
  port: 18082
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: notepad-web
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
  # 配置静态资源
#  resources:
#    static-locations: ["classpath:/templates/","classpath:/static/js/"]
feign:
  hystrix:
    enabled: true
#超时配置
ribbon:
  # Feign请求读取数据超时时间
  ReadTimeout: 300000
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 熔断超时设置，默认为1秒
            timeoutInMilliseconds: 10000
          #  隔离模式使用信号量隔离SEMAPHORE 默认值是线程隔离THREAD
          strategy: SEMAPHORE